config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'

  get 'home/about' => 'homes#about'
  
  get 'searchs/search' => 'searchs#search'

  resources :users, only: [:show, :index, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:show, :index, :edit, :create, :update] do
    resources :favorites, only: [:create,]
    delete 'favorites' => 'favorites#destroy', as:'favorite'
    resources :comments, only: [:create, :destroy]
  end
  
  
  
  

  delete 'books/:id' => 'books#destroy', as:'destroy_book'
  
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { in: 2..20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  
  
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_user, through: :followed, source: :follower
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    following_user.include?(user)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.order(:created_at)

    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    @two = @books.created_2days
    @three = @books.created_3days
    @four = @books.created_4days
    @five = @books.created_5days
    @six = @books.created_6days

  end


  def search
    @user = User.find(params[:user_id])
    @book = Book.new
    @books = @user.books.order(:created_at)

    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      @search_book = @books.where(['created_at LIKE ?',"#{params[:created_at]}%"]).count
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<h3>検索結果</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div>
  <div class="container">
    <div class="row">
      <div class="col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User Info</h2>
        <% if @user.errors.any? %>
         <div id="error">
          <%= @user.errors.count %>error prohibited this obj from being saved:
          <ul>
           <% @user.errors.full_messages.each do |message| %>
            <%= message %>
           <% end %>
          </ul>
         </div>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
        <p>Name</p>
        <%= f.text_field :name, class:"form-control" %>
        <p>Image</p>
        <%= f.attachment_field :profile_image %>
        <p>Introduction</p>
        <%= f.text_area :introduction, class:"form-control" %><br>
        <%= f.submit 'Update User', class:"btn btn-secondary" %>
        <% end %><br>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

            <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.following_user.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followed_user.count, user_followers_path(@user) %></th>
          </tr>
        </table>
        <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
        <span class="fas fa-user-cog"></span>
        <% end %>
        <h2>New book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-inverse">
          <thead>
           <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
            <th></th>
            <th></th>
           </tr>
          </thead>
          <tbody>
           <% @users.each do |user| %>
           <tr>
             <th>
               <%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               </th>
             <th><%= user.name %></th>
             <th><p>フォロー数:<%= user.following_user.count %></p></th>
             <th><p>フォロワー数:<%= user.followed_user.count %></p></th>
             <th>
               <% if user == current_user %>
               <% else %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationship_path(id: user.id, user_id: user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(id: user.id, user_id: user.id), method: :post %>
                  <% end %>
               <% end %>
               
             </th>
             <th><%= link_to "Show", user_path(user.id) %></th>
           </tr>
           <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>

app/views/users/search.js.erb
$("#search_after").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.following_user.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followed_id_user.count, user_followers_path(@user) %></th>
          </tr>
        </table>
        <% if @user == current_user %>
          <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
          <span class="fas fa-user-cog"></span>
          <% end %>
        <% else %>
          <% if current_user.following?(@user) %>
            <%= link_to "Unfollow", user_relationship_path(@user), class:"btn btn-info", method: :delete %>
          <% else %>
            <%= link_to "Follow", user_relationships_path(@user), class:"btn btn-success",method: :post %>
          <% end %>
        <% end %>
        <h2>New book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
           <tr>
             <th>
               <%= link_to user_path(@user) do %>
               <%= attachment_image_tag @user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %>
               </th>
             <th><%= link_to book.title, book_path(book.id) %></th>
             <th><%= book.body %></th>
             <th><p>コメント件数：<%= book.comments.count %></p></th>
           </tr>
           <% end %>
          </tbody>
        </table>

        <%= form_with url: user_search_path(@user), method: :get, remote:true do |f| %>
         <%= f.date_field :created_at %>
         <%= f.submit '検索', class:"btn btn-primary" %>
        <% end %>

        <div id="search_after" >
          <% if @search_book.present? %>
           <%= render 'search', search_book: @search_book %>
          <% end %>
        </div>


      </div>

    </div>
  </div>
</body>