config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'

  get 'home/about' => 'homes#about'
  
  get 'searchs/search' => 'searchs#search'

  resources :users, only: [:show, :index, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:show, :index, :edit, :create, :update] do
    resources :favorites, only: [:create,]
    delete 'favorites' => 'favorites#destroy', as:'favorite'
    resources :comments, only: [:create, :destroy]
  end
  
  
  
  

  delete 'books/:id' => 'books#destroy', as:'destroy_book'
  
  

end

app/models/book.rb
class Book < ApplicationRecord


  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  
  scope :created_2days, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3days, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4days, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5days, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6days, -> { where(created_at: 6.day.ago.all_day) }
  
  
  
  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @booki = Book.find(params[:id])
    @book = Book.new
    @user = @booki.user
    @comment = Comment.new
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book)
    else
       render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private

 def book_params
   params.require(:book).permit(:title, :body)
 end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </table>
        <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <span class="fas fa-user-cog"></span>
        <% end %>
        <h2>New book</h2>
        <%= form_with model:book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>

app/views/books/edit.html.erb
<div>
  <div class="container">
    <div class="row">
      <div class="col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
         <div class="error">
         <%= @book.errors.count %>error prohibited this obj from being saved:
         <ul>
          <% @book.errors.full_messages.each do |message| %>
           <%= message %>
          <% end %>
         </ul>
         </div>
        <% end %>
        <%= form_with model:@book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class:"form-control" %>
        <p>Opinion</p>
        <%= f.text_area :body, class:"form-control" %><br>
        <%= f.submit 'Update Book', class:"btn btn-success" %>
        <% end %><br>
        <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
      <% if @book.errors.any? %>
       <div class="error">
       <%= @book.errors.count %>error prohibited this obj from being saved:
       <ul>
       <% @book.errors.full_messages.each do |message| %>
        <%= message %>
       <% end %>
       </ul>
       </div>
      <% end %>

      <%= render 'books/list', book: @book, user: @user %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            <th></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
           <tr>
             <th>
               <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %>
               </th>
             <th><%= link_to book.title, book_path(book.id) %></th>
             <th><%= book.body %></th>
             <th class="book_<%= book.id %>">
                 <%= render 'favorites/favorite2-button', booki: book %>
             </th>
             <th><p>コメント数：<%= book.comments.count %></p></th>
           </tr>
           <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>

app/views/books/show.html.erb
<body>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', book: @book, user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          
           <tr>
            <th><%= link_to user_path(@booki.user) do %>
               <%= attachment_image_tag @booki.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <% end %><br>
               <%= link_to @user.name, user_path(@booki.user) %>
               </th>
            <th><%= link_to @booki.title, book_path(@booki.id) %></th>
            <th><%= @booki.body %></th>
            <% if @booki.user == current_user %>
            <th><%= link_to "Edit", edit_book_path(@booki) ,class:"btn btn-sm btn-success" %></th>
            <th><%= link_to "Destroy", destroy_book_path(@booki) , method: :delete , "data-confirm" => "本当に消しますか？" ,class:"btn btn-sm btn-danger" %></th>
            <% end %>



            <th class="book_<%= @booki.id %>">
              <%= render 'favorites/favorite-button', booki: @booki %>
            </th>
            <th class="comment-view">
                <p>コメント件数：<%= @booki.comments.count %></p>
            </th>


           </tr>
        </table>
        
        
         <table>
          <tbody id="comment_area">
            <%= render 'comments/comment', booki: @booki %>
          </tbody>
        </table>

        
        <div class="new-comment" >
            <%= form_with(model:[@booki, @comment], remote:true) do |f| %>
            <%= f.text_area :comment, size:"80x6", class:"inputComment" %><br>
            <%= f.submit "送信" %>
            <% end %>
        </div>
      </div>

    </div>
  </div>
</body>